import { onAccountConnect } from '@/api/on-connects'
import '../../styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  await onAccountConnect()

  return (
    <html lang="br">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
