import { ThemeContextProvider } from "@/contexts/ThemeContext"
import '../../../styles/globals.css'
import { Open_Sans } from "next/font/google"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const opensans = Open_Sans({ subsets: ['latin'] })

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <ThemeContextProvider
          attribute='class'
          defaultTheme='light'
        >
          {children}
        </ThemeContextProvider>  
      </body>
    </html>
  )
}
